name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Install dependencies
        run: npm i
      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        with:
          run: gulp test --coverage
      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./coverage/cobertura-coverage.xml
          threshold: 80.123
          fail: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: gulp lint

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Bower
        run: gulp bower
      - name: Build
        run: gulp build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
